### PR TITLE
Prepare for production deployment

### PR DESCRIPTION
**Pull request by ArmaanT**
This PR sets up the codebase for being run in production.
## Changes
1. Clean Django Migrations
2. Change the Django admin header text 
3. Use environment variables for sensitive information
4. Support using a MySQL DB in production and an SQLite DB in development

## Environment Variables
The following environment variables need to be set on the production server:
`PLATFORM_ENV` to `prod`
`SECRET_KEY` to a private secret key
`DB_PASSWORD` to the password for the platform SQL account

### CODE REVIEW

**Comment by kirubarajan** [comment]
Everything looks great! Some style issues that I'm cleaning up in a commit are: 
- Reorder imports so that it follows the layers of abstraction
- Making imports absolute (so that script location doesn't matter)
- Some PEP8 stuff (long lines etc.)

**Comment by kirubarajan** [comment]
Added static support. Django will serve static files from `/static`. Before deploying, we have to run `python manage.py collectstatic`, and commit the static folder it generates (shouldn't be >5mb). If the static folder gets too big to keep in version control, we can migrate to S3.

**Comment by ArmaanT** [comment]
LGTM. I just added a few commits to explicitly define values for `PLATFORM_ENV`, to add newlines to the end of files without them, and to start tracking the static files.

**Comment by kirubarajan** [comment]
DOPE

**Pull request merged**
