### PR TITLE
Fix platform deployment, upgrade to Python 3.11

### PR DESCRIPTION
**Pull request by mureytasroc**
This PR fixes prod platform deployment by updating our pinned version of black, and upgrading to Python 3.11.

It also fixes tests and aims to get platform CI working / deploying again.

To do this, we bumped the debian version of `shibboleth-sp-nginx` from 10 (buster) to 12 (bookworm) in [this PR](https://github.com/pennlabs/infrastructure/pull/183).

### CODE REVIEW

**Comment by mureytasroc** [comment]
A secret was not exposed in this PR, gitguardian is just detecting the hardcoded get-pip commit hash as a secret (it's not secret - just updating the previous pinned get-pip commit to the latest merged commit).

**Comment by mureytasroc** [comment]
Didn't add any secrets in this PR... does this mean there were existing hardcoded secrets in the platform backend code somewhere? Not worth addressing in this PR.

**Review by joyliu-q — APPROVED** [review]
LGTM!

**Comment by mureytasroc** [comment]
Can we reopen this?

**Comment by mureytasroc** [comment]
Nvm just opened a new PR [here](https://github.com/pennlabs/platform/pull/169).

**Comment by mureytasroc** [comment]
This PR is continued [here](https://github.com/pennlabs/platform/pull/170).

**Pull request merged**
